name: Compilation Check

on:
  push:
    branches:
      - '**'

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Display current branch
      run: echo "Current branch: ${{ github.ref }}"

    - name: Build project
      run: make

  build-Mac:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Display current branch
      run: echo "Current branch: ${{ github.ref }}"

    - name: Build project
      run: make
